version: '3'
services:
  python37:
    restart: always
    build: .
    container_name: 'python37'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
    environment:
      TZ: Asia/Tokyo
