version: '3'
services:
  ruby30:
    restart: always
    build: .
    container_name: 'ruby30'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
    environment:
      TZ: Asia/Tokyo
