version: '3'
services:
  codenize-tools:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'codenize-tools'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
    environment:
      TZ: Asia/Tokyo
